// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdi8n58aTJQ6XmaaC3IaZOF5snx5Tqb50',
    appId: '1:303662826191:web:0d032ec396572e7da9adba',
    messagingSenderId: '303662826191',
    projectId: 'datemate-3d69b',
    authDomain: 'datemate-3d69b.firebaseapp.com',
    storageBucket: 'datemate-3d69b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDSmRGhkc5Ucbn81wF80jkURHbSYW6sfS0',
    appId: '1:303662826191:android:f6b67bbe06b7ad5ca9adba',
    messagingSenderId: '303662826191',
    projectId: 'datemate-3d69b',
    storageBucket: 'datemate-3d69b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAG5i6Omm8s-E-lsOrbYWjLoN_JFWe-TJU',
    appId: '1:303662826191:ios:37a72adcc1230628a9adba',
    messagingSenderId: '303662826191',
    projectId: 'datemate-3d69b',
    storageBucket: 'datemate-3d69b.firebasestorage.app',
    iosBundleId: 'com.example.datemate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAG5i6Omm8s-E-lsOrbYWjLoN_JFWe-TJU',
    appId: '1:303662826191:ios:37a72adcc1230628a9adba',
    messagingSenderId: '303662826191',
    projectId: 'datemate-3d69b',
    storageBucket: 'datemate-3d69b.firebasestorage.app',
    iosBundleId: 'com.example.datemate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdi8n58aTJQ6XmaaC3IaZOF5snx5Tqb50',
    appId: '1:303662826191:web:23e39deaf50e942da9adba',
    messagingSenderId: '303662826191',
    projectId: 'datemate-3d69b',
    authDomain: 'datemate-3d69b.firebaseapp.com',
    storageBucket: 'datemate-3d69b.firebasestorage.app',
  );

}